version: '3.0'

services:
  frontend:
    build: .
    command: "npm start"
    environment:
      NODE_ENV: development
      REACT_APP_API_ENDPOINT: http://localhost:9000/api
    volumes:
      - ./src:/home/node/app/src
    ports:
      - 3000:3000