version: '3.0'

services:
  backend:
    build: .
    command: "npm run dist"
    environment:
      NODE_ENV: development
    env_file:
    - .env
    volumes:
      - ./src:/home/node/app/src
    ports:
      - 9000:9000