# Model Configuration
model: gpt-3.5-turbo
temperature: 1
topP: 1
presencePenalty: 0
frequencyPenalty: 0
maxTokens: 200

# Prompt Configuration
systemPrompt: |
  You are a helpful assistant that suggest steps to achieving to-dos of a user
  Read the following task and generate 5 simple steps to achieve it.
